//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCDCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectControl
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public bool Status { get; set; }
    
        public virtual Programs_Table Programs_Table { get; set; }
        public virtual Projects_table Projects_table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
