//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCDCRSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivities_Table
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> Srarttime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> ActivitiesCategoryID { get; set; }
        public Nullable<int> ActivityPeopleCategory { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CorporationID { get; set; }
        public string ActivatorName { get; set; }
        public string ActivatorMobil { get; set; }
        public string CorporationContactRing { get; set; }
        public string CorporationPhone { get; set; }
        public Nullable<int> TotalPresence { get; set; }
        public Nullable<int> TotalMale { get; set; }
        public Nullable<int> TotlFemal { get; set; }
        public string Emergency_Intervention { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SaturdayDay { get; set; }
        public string SundayDay { get; set; }
        public string MondayDay { get; set; }
        public string tuesdayDay { get; set; }
        public string wednesdayDay { get; set; }
        public string thursdayDay { get; set; }
    
        public virtual ActivitiesCategory_Table ActivitiesCategory_Table { internal get; set; }
        public virtual ActivityPeopleCategory_Table ActivityPeopleCategory_Table { internal get; set; }
        public virtual City_Table City_Table { internal get; set; }
        public virtual Corporation_Table Corporation_Table { internal get; set; }
        public virtual Projects_table Projects_table { internal get; set; }
        public virtual Province_Table Province_Table { internal get; set; }
        public virtual Users_Table Users_Table { internal get; set; }
    }
}
